[package]
name = "gallery-grabber"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1"
clap = { version = "4.5", features = ["derive"]}
rayon = "1.9"
reqwest = {  version = "0.11", features = ["blocking"] }
url = "2.5"
