[package]
name = "gallery-grabber"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"]}
rayon = "1.11"
reqwest = {  version = "0.12", features = ["blocking"] }
